spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 20
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache.use_query_cache: false
        cache.use_second_level_cache: false
        cache.use_structured_entries: false
        cache.use_minimal_puts: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog_db?serverTimezone=UTC
    username: root
    password: testtest
#    driverClassName: com.mysql.jdbc.Driver