spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 20
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache.use_query_cache: false
        cache.use_second_level_cache: false
        cache.use_structured_entries: false
        cache.use_minimal_puts: false
      liquibase:
        enabled: true #this is optional as enabled by default
        change-log: classpath:/liquibase-outputChangeLog.xml
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog_db?serverTimezone=UTC
    username: root
    password: testtest
    changeLogFile: src/main/resources/liquibase-outputChangeLog.xml

#    driverClassName: com.mysql.jdbc.Driver